language: ruby
rvm:
  - 1.9.2
env:
  global:
    - secure: "AurP4QaJAZox2KwKpymG6prbOILjN7ynoSlR7y7csNZI3BXAm/0udxIWaL1Q\nb4f6yqo7osm0ZgxBadTQ9FoqMWnpIg37C7A/2+sMhJpxVAB5GgUAu0i/DMjM\nWEYccNDHsc7M+zFuMPXvhf65D2XRhKDzsRHHGxcWAT+QyGkE77w="
branches:
  only:
    - master
before_script:
  - sed -i.bak s/--BUILD_VERSION--/$TRAVIS_BUILD_NUMBER/g source/layouts/layout.erb 
script: bundle exec middleman build
after_success:
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then echo "Deployments are only done for the master branch. "; exit 0; fi
  - echo "Deploying build $TRAVIS_BUILD_NUMBER to cf-docs-contrib.cloudfoundry.com"
  - ./deploy_to_cloudfoundry.sh